### ISSUE TITLE
[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: EACCES: permission denied, mkdir '/opt/IBM/FHE-Workspace/build' 

### ISSUE THREAD

**Issue by QinLongFei** [IBM/fhe-toolkit-linux#23]
**Describe the bug**

When I access https://127.0.0.1:8443/, Firefox always output an error like:

[rollbar] Unhandled exception: Unhandled Promise rejection: Post-folder-open Error: EACCES: permission denied, mkdir '/opt/IBM/FHE-Workspace/build' {"folder":{"uri":{"$mid":1,"fsPath":"/opt/IBM/FHE-Workspace","external":"file:///opt/IBM/FHE-Workspace","path":"/opt/IBM/FHE-Workspace","scheme":"file"},"name":"FHE-Workspace","index":0}}

**To Reproduce**
1. git clone https://github.com/IBM/fhe-toolkit-linux.git
2. ./FetchDockerImage.sh centos
3. ./RunToolkit.sh -p centos
4. Access https://127.0.0.1:8443/ with Firefox
5. See this error.

**Screenshots**
![image](https://user-images.githubusercontent.com/14818295/90377763-09ffa600-e0ab-11ea-9a82-4acf8a5c114e.png)

**Environment (please complete the following information):**
 - Host Info (The machine hosting the FHE Toolkit Docker container), please provide the output of running the following commands in a termina window:
   - `uname -a`
Linux localhost.localdomain 4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
   - `ulimit -a`
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 6978
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 6978
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

 - Docker version (run `docker -v` in Terminal):
Docker version 19.03.12, build 48a66213fe
 - Toolkit platform (Fedora, CentOS, Ubuntu):
CentOS

**Additional context**

**Comment by dowem** [comment]
Hi @QinLongFei ! 

Can you try running the toolkit with the  -s option for me?  It defniitely appears that the persistent storage is broken for you somehow. I am wondering if it is because your system will not let the script write to /opt/IBM/ i nthe file system.  If you add the "-s" flag it may bypass the error so you can at least experiment with the toolkit even if your data changes are not preserved across runs. 

Simply make step 3: 
./RunToolkit.sh -p -s centos

Please let me know if this helps you get any further. In the meantime, I will think more about what might be causing this issue.

**Comment by QinLongFei** [comment]
Hi, @dowem ,

Thanks for your reply!

Now, It can continue work with "-s" option.

Thanks
