### ISSUE TITLE
Permission denied during kit configuration

### ISSUE THREAD

**Issue by SebastianSavi** [IBM/fhe-toolkit-linux#28]
**Describe the bug**
After following the 4 first steps of the GettingStarted.md and selecting the "kit" in the toolkit, the configuration outputs the following error:
```
[main] Configuring folder: FHE-Workspace 
[rollbar] Unhandled exception: Failed writing to file /opt/IBM/FHE-Workspace/build/.cmake/api/v1/query/client-vscode/query.json Error: EACCES: permission denied, mkdir '/opt/IBM/FHE-Workspace/build' {}
[driver] Failed to configure project
```
I tried to restart the container but the issue persists.

**To Reproduce**
1. Clone the IBM FHE Toolkit Repository
2. Fetch the Toolkit Docker Images by running `./FetchDockerImage.sh ubuntu`
3. Rune the toolkit by running `./RunToolkit.sh -p ubuntu`
4. Open toolkit in browser by visiting `https://127.0.0.1:8443/` 
5. Select any of the kits that the toolkit prompts you to select
6. See error in the Output window at the end of configuration

**Expected behavior**
Expected to see the kit configuration end with no error.

**Environment (please complete the following information):**
 - Host Info (The machine hosting the FHE Toolkit Docker container), please provide the output of running the following commands in a termina window:
   - `uname -` output: `Linux daniel-ThinkPad 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
   - `ulimit -a` output: 
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 29316
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 29316
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

 - Docker version (run `docker -v` in Terminal): `Docker version 19.03.12, build 48a66213fe`
 - Toolkit platform (Fedora, CentOS, Ubuntu): Ubuntu

**Comment by christianepeters** [comment]
I'm having the same issue. The problem is that the `docker run` command doesn't pass on the permissions correctly. 

This is what the `./RunToolkit.sh -p ubuntu` call does:
```
docker run -d --name fhe-toolkit-ubuntu  -v /home/username/Documents/fhe-toolkit-linux/FHE-Toolkit-Workspace:/opt/IBM/FHE-Workspace  -p 8443:8443 ibmcom/fhe-toolkit-ubuntu
```
The problem is that Ubuntu (also CentOS) puts default permissions of the FHE-Toolkit-Workspace repository to 755 which does not allow the container to write into the FHE-Workspace folder locally. 

If I used `chmod 777 FHE-Toolkit-Workspace`, the Docker container is able to write into the local directory, making all computations persistent. That's quick and dirty.

Better would be to fix the `./RunToolkit.sh` to pass on the permissions during the folder bind.

**Comment by christianepeters** [comment]
As an addition: I noted that MacOS is more forthcoming than Linux. When running the Linux toolkit (CentOS) in the terminal on my Mac, the command `RunToolkit.sh -p centos` triggers a pop-up window asking me to give permissions to let the container write to my Documents. On the other hand, CentOS and Ubuntu will take note of the issue but won't do anything about it.

**Comment by boland25** [comment]
When running this on Linux we realize that there is a permissions issue on the persistent data space that is created on the user's local disk, `FHE-Toolkit-Workspace` directory.  Because this is shared space between the local disk and the dockerimage, there is confusion on the docker side as to who the owner is.  

It is a problem that we are working towards to find an ideal solution, but in the meantime there is a quick fix workaround. 

To get pass the permission issue in the `PersistData.sh` file, at the end of the file, line 260 or beyond, add a change permission command to the directory such as this...

`chmod -R 777 $PERSISTENT_FHE_WORKSPACE_PATH`

This will allow the fhe user on the docker image to access and write to the necc. files to run the demos.
