### ISSUE TITLE
 https://127.0.0.1:8443/ browser empty error

### ISSUE THREAD

**Issue by baoyuwang** [IBM/fhe-toolkit-linux#84]
Hi All,

I have successful installation and run FHE-Toolkit on Linux, but when I want to access UI in browser with  https://127.0.0.1:8443/, It always display empty without any content, I used curl to verify,  the result HTML has content,   any tips will be helpful,  thanks a lot.

**Comment by boland25** [comment]
Hi @baoyuwang, thanks for posting your issue.  In order to try and figure out more about what is happened, can you tell us more about what system you are trying to run it on, and what browser you are trying to view it in?  Also, because we are providing for demo purposes a self signed certificate for https, there is a "warning" screen that pops up initially that you need to click through and accept.  Can you confirm that process is happening?  thanks!

**Comment by dowem** [comment]
@baoyuwang have you had a chance to respond to Greg's request for more info to help us track down the issue you are seeing?

**Comment by boland25** [comment]
going to close this out for lack of response, but if any problems popup feel free to re-open
